///////////////////////////////////////////////////////////////////////////
//
//  This file is part of RTIMULib
//
//  Copyright (c) 2014-2015, richards-tech, LLC
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of
//  this software and associated documentation files (the "Software"), to deal in
//  the Software without restriction, including without limitation the rights to use,
//  copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
//  Software, and to permit persons to whom the Software is furnished to do so,
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
//  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
//  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
//  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
//  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


#include "RTIMULib.h"
#include <cmath>
#include <cstring>
#include <unistd.h>

int main()
{
    int sampleCount = 0;
    int sampleRate = 0;
    uint64_t rateTimer;
    uint64_t displayTimer;
    uint64_t now;
    
    // Arrays to store last 10 samples for averaging
    const int BUFFER_SIZE = 10;
    double gyroPitch[BUFFER_SIZE];
    double gyroRoll[BUFFER_SIZE];
    double gyroYaw[BUFFER_SIZE];
    double temperature[BUFFER_SIZE];
    double pressure_samples[BUFFER_SIZE];
    double humidity_samples[BUFFER_SIZE];
    
    // Index for circular buffer and sample count
    int bufferIndex = 0;
    int numSamples = 0;
    int totalSampleCount = 0;  // Total samples displayed (for labeling output)

    //  using RTIMULib here allows it to use the .ini file generated by RTIMULibDemo.

    RTIMUSettings * settings = new RTIMUSettings("RTIMULib");

    RTIMU * imu = RTIMU::createIMU(settings);
    RTPressure * pressure = RTPressure::createPressure(settings);
    RTHumidity * humidity = RTHumidity::createHumidity(settings);

    if ((imu == NULL) || (imu->IMUType() == RTIMU_TYPE_NULL)) 
	{
        printf("No IMU found\n");
        exit(1);
    }

    //  This is an opportunity to manually override any settings before the call IMUInit

    //  set up IMU

    imu->IMUInit();

    //  this is a convenient place to change fusion parameters

    imu->setSlerpPower(0.02);
    imu->setGyroEnable(true);
    imu->setAccelEnable(true);
    imu->setCompassEnable(true);

    //  set up pressure sensor

    if (pressure != NULL)
    {
        pressure->pressureInit();
    }

    //  set up humidity sensor

    if (humidity != NULL)
    {
        humidity->humidityInit();
    }

    //  set up for rate timer

    rateTimer = displayTimer = RTMath::currentUSecsSinceEpoch();

    //  now just process data

    while (1) 
	{
		/* HINT: The whole purpose of the weird way this is written is to poll the 
		 *       IMU at its recommended rate, but display the data at a rate that may be different.
         *		 Not polling at the correct rate can result in weird readings.
		 *
		 **/
		
        //  poll at the rate recommended by the IMU
		
        usleep(imu->IMUGetPollInterval() * 1000);

        while (imu->IMURead()) 
		{
            RTIMU_DATA imuData = imu->getIMUData();

            //  add the pressure data to the structure

            if (pressure != NULL)
            {
                pressure->pressureRead(imuData);
            }

            //  add the humidity data to the structure

            if (humidity != NULL)
            {
                humidity->humidityRead(imuData);
            }

            sampleCount++;

            now = RTMath::currentUSecsSinceEpoch();

            //  display 1 time per second
			//  HINT: The code inside this "if" statement executes once per second.
			//        Put all of your code to print/calculate current and average IMU data inside here.
			//        You shouldn't need to modify anything outside of this "if" statement.
			//        The IMU is polled at the recommended rate, but this "if" statement ensures that the  
            //        values are only displayed at a certain interval.			
            if ((now - displayTimer) > 1000000) 
			{
                // Store current sensor values in circular buffer (convert radians to degrees for pose)
                const double radToDeg = 180.0 / M_PI;
                gyroPitch[bufferIndex] = imuData.fusionPose.x() * radToDeg;
                gyroRoll[bufferIndex] = imuData.fusionPose.y() * radToDeg;
                gyroYaw[bufferIndex] = imuData.fusionPose.z() * radToDeg;
                temperature[bufferIndex] = imuData.temperature;
                pressure_samples[bufferIndex] = imuData.pressure;
                humidity_samples[bufferIndex] = imuData.humidity;
                
                // Update sample count and buffer index
                if (numSamples < BUFFER_SIZE) {
                    numSamples++;
                }
                bufferIndex = (bufferIndex + 1) % BUFFER_SIZE;
                totalSampleCount++;

                // Calculate averages
                double avgPitch = 0, avgRoll = 0, avgYaw = 0;
                double avgTemp = 0, avgPressure = 0, avgHumidity = 0;
                
                for (int i = 0; i < numSamples; i++) {
                    avgPitch += gyroPitch[i];
                    avgRoll += gyroRoll[i];
                    avgYaw += gyroYaw[i];
                    avgTemp += temperature[i];
                    avgPressure += pressure_samples[i];
                    avgHumidity += humidity_samples[i];
                }
                
                avgPitch /= numSamples;
                avgRoll /= numSamples;
                avgYaw /= numSamples;
                avgTemp /= numSamples;
                avgPressure /= numSamples;
                avgHumidity /= numSamples;
                
                // Print current values
                printf("\n=== Sample #%d (Sample Rate: %d) ===\n", totalSampleCount, sampleRate);
                printf("CURRENT VALUES:\n");
                printf("  Pitch: %6.2f°, Roll: %6.2f°, Yaw: %6.2f°\n", 
                       gyroPitch[(bufferIndex + BUFFER_SIZE - 1) % BUFFER_SIZE],
                       gyroRoll[(bufferIndex + BUFFER_SIZE - 1) % BUFFER_SIZE],
                       gyroYaw[(bufferIndex + BUFFER_SIZE - 1) % BUFFER_SIZE]);
                
                printf("  Temperature: %6.2f°C\n", imuData.temperature);
                printf("  Pressure: %7.1f hPa\n", imuData.pressure);
                printf("  Humidity: %6.1f%%\n", imuData.humidity);
                
                // Print averages of last 10 samples
                printf("\nAVERAGE OF LAST %d SAMPLES:\n", numSamples);
                printf("  Pitch: %6.2f°, Roll: %6.2f°, Yaw: %6.2f°\n", 
                       avgPitch, avgRoll, avgYaw);
                printf("  Temperature: %6.2f°C\n", avgTemp);
                printf("  Pressure: %7.1f hPa\n", avgPressure);
                printf("  Humidity: %6.1f%%\n", avgHumidity);

                fflush(stdout);
                displayTimer = now;//HINT: LEAVE THIS LINE ALONE!!!
            }

            //  update rate every second

            if ((now - rateTimer) > 1000000) 
			{
                sampleRate = sampleCount;
                sampleCount = 0;
                rateTimer = now;
            }
        }
    }
}